# Generated by Django 5.1.2 on 2024-11-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitec', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
