# Generated by Django 5.1.2 on 2024-11-08 00:56

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vitec', '0002_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=75)),
                ('make', models.CharField(max_length=50)),
                ('notes', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Centrifuge',
            fields=[
                ('instrument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vitec.instrument')),
                ('rpm_test', models.CharField(max_length=200)),
                ('rpm_actual', models.CharField(max_length=200)),
            ],
            bases=('vitec.instrument',),
        ),
        migrations.CreateModel(
            name='Pipette',
            fields=[
                ('instrument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vitec.instrument')),
                ('pipette_type', models.CharField(max_length=100)),
                ('volume', models.CharField(max_length=100)),
            ],
            bases=('vitec.instrument',),
        ),
        migrations.CreateModel(
            name='Thermometer',
            fields=[
                ('instrument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vitec.instrument')),
                ('thermometer_type', models.CharField(max_length=100)),
                ('temperature_test', models.DecimalField(decimal_places=3, max_digits=6)),
                ('temperature_actual', models.DecimalField(decimal_places=3, max_digits=6)),
                ('humidity_test', models.DecimalField(decimal_places=1, max_digits=4)),
                ('humidity_actual', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            bases=('vitec.instrument',),
        ),
        migrations.AddField(
            model_name='instrument',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitec.institution'),
        ),
        migrations.CreateModel(
            name='Service_Order',
            fields=[
                ('so_number', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('instrument_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitec.institution')),
            ],
        ),
    ]
