# Generated by Django 5.1.2 on 2024-11-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitec', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrifuge',
            name='rpm_actual',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='centrifuge',
            name='rpm_test',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='thermometer',
            name='humidity_actual',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='thermometer',
            name='humidity_test',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='thermometer',
            name='temperature_actual',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='thermometer',
            name='temperature_test',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
