# Generated by Django 5.1.2 on 2024-11-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitec', '0004_alter_centrifuge_rpm_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='notes',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
