# Generated by Django 5.1.2 on 2024-11-25 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitec', '0005_alter_instrument_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPM',
            fields=[
                ('instrument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vitec.instrument')),
                ('rpm_type', models.CharField(max_length=100)),
                ('rpm_test', models.CharField(blank=True, max_length=200)),
                ('rpm_actual', models.CharField(blank=True, max_length=200)),
            ],
            bases=('vitec.instrument',),
        ),
        migrations.RenameModel(
            old_name='Thermometer',
            new_name='Temperature',
        ),
        migrations.DeleteModel(
            name='Centrifuge',
        ),
    ]
