# Generated by Django 5.1.2 on 2024-11-25 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitec', '0006_rpm_rename_thermometer_temperature_delete_centrifuge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperature',
            old_name='thermometer_type',
            new_name='temperature_type',
        ),
    ]
