# Generated by Django 5.1.2 on 2024-11-25 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitec', '0007_rename_thermometer_type_temperature_temperature_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='type',
            new_name='instrument_type',
        ),
    ]
