# Generated by Django 5.1.2 on 2024-12-21 06:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitec', '0013_alter_rpm_rpm_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpm',
            name='rpm_actual',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(error_messages={'invalid': 'Please enter a valid whole number for each RPM Actual value.'}), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='rpm',
            name='rpm_test',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(error_messages={'invalid': 'Please enter a valid whole number for each RPM Test value.'}), blank=True, default=list, size=None),
        ),
    ]
