# Generated by Django 5.1.2 on 2025-01-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitec', '0014_alter_rpm_rpm_actual_alter_rpm_rpm_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_order',
            name='additional_contact',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='service_order',
            name='department',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
