# Generated by Django 5.1.4 on 2025-01-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitec', '0016_rpm_timer_actual_rpm_timer_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpm',
            name='model',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='temperature',
            name='model',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
    ]
