# Generated by Django 5.1.4 on 2025-01-28 01:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitec', '0017_rpm_model_temperature_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperature',
            name='temperature_test',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='temperature_actual',
        ),
        migrations.AddField(
            model_name='temperature',
            name='temperature_test',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DecimalField(max_digits=6, decimal_places=3),
                blank=True,
                default=list
            ),
        ),
        migrations.AddField(
            model_name='temperature',
            name='temperature_actual',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DecimalField(max_digits=6, decimal_places=3),
                blank=True,
                default=list
            ),
        ),
    ]
