# Generated by Django 5.1.4 on 2025-01-28 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitec', '0018_alter_temperature_temperature_actual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microscope',
            fields=[
                ('instrument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vitec.instrument')),
                ('microscope_type', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, default='N/A', max_length=50)),
            ],
            bases=('vitec.instrument',),
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('instrument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vitec.instrument')),
                ('timer_type', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, default='N/A', max_length=50)),
            ],
            bases=('vitec.instrument',),
        ),
    ]
