# Generated by Django 5.1.4 on 2025-01-28 23:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitec', '0019_microscope_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='timer_actual',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DurationField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='timer',
            name='timer_test',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DurationField(), blank=True, default=list, size=None),
        ),
    ]
