# Generated by Django 5.1.4 on 2025-01-29 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitec', '0020_timer_timer_actual_timer_timer_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='microscope',
            old_name='model',
            new_name='microscope_model',
        ),
        migrations.RenameField(
            model_name='rpm',
            old_name='model',
            new_name='rpm_model',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='model',
            new_name='temperature_model',
        ),
        migrations.RenameField(
            model_name='timer',
            old_name='model',
            new_name='timer_model',
        ),
    ]
