# Generated by Django 5.1.4 on 2025-01-29 02:00

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitec', '0021_rename_model_microscope_microscope_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThermoRPM',
            fields=[
                ('instrument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vitec.instrument')),
                ('thermoRPM_type', models.CharField(max_length=100)),
                ('thermoRPM_model', models.CharField(blank=True, default='N/A', max_length=50)),
                ('rpm_test', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('rpm_actual', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('temperature_test', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=6), blank=True, default=list, size=None)),
                ('temperature_actual', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=3, max_digits=6), blank=True, default=list, size=None)),
                ('timer_test', django.contrib.postgres.fields.ArrayField(base_field=models.DurationField(), blank=True, default=list, size=None)),
                ('timer_actual', django.contrib.postgres.fields.ArrayField(base_field=models.DurationField(), blank=True, default=list, size=None)),
            ],
            bases=('vitec.instrument',),
        ),
    ]
