# Generated by Django 5.1.4 on 2025-01-29 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitec', '0023_airflow_balance_phmeter_refrigeration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phmeter',
            name='unit_type',
        ),
    ]
