# Generated by Django 5.1.4 on 2025-01-30 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitec', '0024_remove_phmeter_unit_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='balanace_model',
            new_name='balance_model',
        ),
    ]
