# Generated by Django 5.1.4 on 2025-01-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitec', '0025_rename_balanace_model_balance_balance_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phmeter',
            name='pH10_actual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phmeter',
            name='pH10_test',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phmeter',
            name='pH4_actual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phmeter',
            name='pH4_test',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phmeter',
            name='pH7_actual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phmeter',
            name='pH7_test',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
