# Generated by Django 5.1.4 on 2025-01-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitec', '0026_alter_phmeter_ph10_actual_alter_phmeter_ph10_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airflow',
            name='filter_leak_test',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='airflow',
            name='uv_light_test',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
