# Generated by Django 5.1.4 on 2025-02-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitec', '0027_alter_airflow_filter_leak_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrigeration',
            name='temperature1_actual',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='refrigeration',
            name='temperature1_test',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='refrigeration',
            name='temperature2_actual',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='refrigeration',
            name='temperature2_test',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='refrigeration',
            name='voltage',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
    ]
