# Generated by Django 5.1.4 on 2025-07-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitec', '0028_refrigeration_temperature1_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='lab_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
