# Generated by Django 5.1.4 on 2025-07-31 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitec', '0029_institution_lab_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='service_order',
            name='institution',
        ),
    ]
