# Generated by Django 5.1.4 on 2025-07-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitec', '0030_remove_instrument_institution_and_more'),
    ]

    operations = [
        # Remove primary key from 'name' field manually using a RunSQL
        migrations.RunSQL(
            sql="ALTER TABLE vitec_institution DROP CONSTRAINT vitec_institution_pkey;",
            reverse_sql="""
                ALTER TABLE vitec_institution 
                DROP CONSTRAINT IF EXISTS vitec_institution_pkey;
            """
        ),
        # Now add the new AutoField primary key
        migrations.AddField(
            model_name='institution',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),  # default gets removed later
            preserve_default=False,
        ),
        # Make 'name' just a normal field
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='institution',
            unique_together={('name', 'contact')},
        ),
    ]
