# Generated by Django 5.1.4 on 2025-07-31 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitec', '0031_institution_id_alter_institution_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vitec.institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service_order',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vitec.institution'),
            preserve_default=False,
        ),
    ]
