# Generated by Django 5.1.4 on 2025-07-31 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitec', '0032_instrument_institution_service_order_institution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='lab_name',
            new_name='department',
        ),
    ]
