# Generated by Django 5.1.4 on 2025-07-31 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitec', '0033_rename_lab_name_institution_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_order',
            name='department',
        ),
    ]
