"""
Django settings for viteccalibrations project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from .base import *


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['vitec-app-366708568649.us-central1.run.app']

# HTTPS settings
CSRF_COOKIE_SECURE = True  # Send CSRF cookie over HTTPS only
SESSION_COOKIE_SECURE = True  # Send session cookie over HTTPS only
CSRF_TRUSTED_ORIGINS = [
    "https://vitec-app-366708568649.us-central1.run.app",
]  # List of trusted origins for CSRF


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "vitecdb",
        "USER": "admin",
        "PASSWORD": "test123",
        "HOST": "/cloudsql/vitec-calibrations-admin:us-central1:vitec-admin-database",
        "PORT": "5432",
    }
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': True,
        },
        # Log database queries (optional but helpful)
        'django.db.backends': {
            'level': 'DEBUG',
            'handlers': ['console'],
        },
    },
}



STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
SESSION_COOKIE_DOMAIN = "vitec-app-366708568649.us-central1.run.app"  # This allows sharing cookies across subdomains
SESSION_COOKIE_SECURE = True  # Ensure this is set for production
SESSION_COOKIE_SAMESITE = 'None'  # Allow cookies to be sent in cross-site requests
CSRF_COOKIE_SAMESITE = 'None'

